
title: C.E. Carter
author: C.E. Carter
email: carterce1997@gmail.com

description: Reformed and reforming commentary.

url: https://chrisevancarter.com

spotify: https://open.spotify.com/show/07Cs1dMToRqjYoestMe13W
apple_podcasts: https://podcasts.apple.com/us/podcast/c-e-carter/id1554885526

auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title

copyright: 2021 Christopher Carter
