
title: C.E. Carter
author: C.E. Carter
email: carterce1997@gmail.com

description: Reformed and Postmillenial study notes, essays, commentary, and other prose.

url: https://chrisevancarter.com

auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title

copyright: 2021 Christopher Carter
