
title: Unapologetics
tagline:

quote: '<i>"My heart I offer to you Lord, promptly and sincerely."</i>'

auto: true
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title

sass:
  sass_dir: _sass
