
title: Telos
author: C.E. Carter
email: carterce1997@gmail.com

description: Reforming commentary.

url: https://chrisevancarter.com

auto: true
markdown: kramdown
permalink: /:year/:month/:day/:title

copyright: 2021 Christopher Carter
