
title: unapologetics
tagline:

quote: '"My heart I offer to you Lord, promptly and sincerely." ~ Calvin'

auto: true
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title

sass:
  sass_dir: _sass
